version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend_app
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
