version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: tuusuario/backend_app:latest  
    container_name: backend_app
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./server/src/environments/.env.production
    environment:
      NODE_ENV: production
    depends_on:
      - db

  frontend:
    image: tuusuario/frontend_app:latest  
    container_name: frontend_app
    restart: always
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
    depends_on:
      - backend

volumes:
  db_data:
