services:
  backend:
    volumes:
      - ./server:/app/server
      - ./domain:/app/domain
      - /app/server/node_modules
    env_file:
      - ./server/src/environments/.env.development
    environment:
      NODE_ENV: development

  frontend:
    volumes:
      - ./client:/client
      - ./domain:/domain
      - /client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
