version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend_app
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app/server          
      - ./domain:/app/domain          
      - /app/server/node_modules     
    env_file:
      - ./server/src/environments/.env
      - ./server/src/environments/.env.development
    environment:
      NODE_ENV: development
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - ./domain:/domain
      - /client/node_modules           
    environment:
      - CHOKIDAR_USEPOLLING=true       
      - HOST=0.0.0.0                   
    depends_on:
      - backend

volumes:
  db_data:
