name: CI/CD - Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend_app:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/backend_app:latest -f Dockerfile .

      - name: Build frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend_app:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/frontend_app:latest ./client

      - name: Push imágenes
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_app:${{ github.sha }}

          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_app:${{ github.sha }}
